### ISSUE TITLE
npm run integration fails

### ISSUE THREAD

**Issue by muthufmass** [filipesilva/angular-quickstart-lib#74]
When I git clone and start fresh.
Everything works on the quickstart-lib except with integration test run

npm run integration 

Error: Angular could not be found on the page http://localhost:8080/.If this is not an Angular application, you may need to turn off waiting for Angular.

Error Log:

[1] [12:54:48] E/protractor - Could not find Angular on page http://localhost:8080/ : retries looking for angular exceeded
[1] F[12:54:58] E/protractor - Could not find Angular on page http://localhost:8080/ : retries looking for angular exceeded
[1] F
[1]
[1] Failures:
[1] 1) QuickStart Lib E2E Tests should display lib
[1]   Message:
[1]     Failed: Angular could not be found on the page http://localhost:8080/.If this is not an Angular application, you may need to turn off waiting for Angular.
[1]                               Please see
[1]                               https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
[1]   Stack:
[1]     Error: Angular could not be found on the page http://localhost:8080/.If this is not an Angular application, you may need to turn off waiting for Angular.
[1]                               Please see
[1]                               https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
[1]         at executeAsyncScript_.then (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/protractor/lib/browser.ts:936:29)
[1]         at ManagedPromise.invokeCallback_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:1366:14)
[1]         at TaskQueue.execute_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2970:14)
[1]         at TaskQueue.executeNext_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2953:27)
[1]         at asyncRun (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2813:27)
[1]         at /Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:676:7
[1]         at <anonymous>
[1]         at process._tickCallback (internal/process/next_tick.js:188:7)
[1]     From: Task: Run beforeEach in control flow
[1]         at UserContext.<anonymous> (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/jasminewd2/index.js:94:19)
[1]     From asynchronous test:
[1]     Error
[1]         at Suite.<anonymous> (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/e2e/app.e2e-spec.ts:5:3)
[1]         at Object.<anonymous> (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/e2e/app.e2e-spec.ts:3:1)
[1]         at Module._compile (module.js:652:30)
[1]         at Object.Module._extensions..js (module.js:663:10)
[1]         at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
[1]   Message:
[1]     Failed: Error while waiting for Protractor to sync with the page: "window.angularis undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
[1]   Stack:
[1]     Error: Error while waiting for Protractor to sync with the page: "window.angular is undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
[1]         at runWaitForAngularScript.then (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/protractor/lib/browser.ts:653:19)
[1]         at ManagedPromise.invokeCallback_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:1366:14)
[1]         at TaskQueue.execute_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2970:14)
[1]         at TaskQueue.executeNext_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2953:27)
[1]         at asyncRun (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2813:27)
[1]         at /Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:676:7
[1]         at <anonymous>
[1]         at process._tickCallback (internal/process/next_tick.js:188:7)Error
[1]         at ElementArrayFinder.applyAction_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/protractor/lib/element.ts:482:23)
[1]         at ElementArrayFinder.(anonymous function).args [as getText] (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/protractor/lib/element.ts:96:21)
[1]         at ElementFinder.(anonymous function).args [as getText] (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/protractor/lib/element.ts:873:14)
[1]         at UserContext.<anonymous> (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/e2e/app.e2e-spec.ts:14:34)
[1]         at /Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/jasminewd2/index.js:112:25
[1]         at new ManagedPromise (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:1067:7)
[1]         at ControlFlow.promise (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2396:12)
[1]         at schedulerExecute (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/jasminewd2/index.js:95:18)
[1]         at TaskQueue.execute_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2970:14)
[1]         at TaskQueue.executeNext_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2953:27)
[1]     From: Task: Run it("should display lib") in control flow
[1]         at UserContext.<anonymous> (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/jasminewd2/index.js:94:19)
[1]         at /Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/jasminewd2/index.js:64:48
[1]         at ControlFlow.emit (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/events.js:62:21)
[1]         at ControlFlow.shutdown_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2565:10)
[1]     From asynchronous test:
[1]     Error
[1]         at Suite.<anonymous> (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/e2e/app.e2e-spec.ts:13:3)
[1]         at Object.<anonymous> (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/e2e/app.e2e-spec.ts:3:1)
[1]         at Module._compile (module.js:652:30)
[1]         at Object.Module._extensions..js (module.js:663:10)
[1]         at Module.load (module.js:565:32)
[1]         at tryModuleLoad (module.js:505:12)
[1]   Message:
[1]     Expected $.length = 3 to equal 0.
[1]     Expected $[0] = Entry({ level: SEVERE, message: 'http://localhost:8080/bundle.js - Failed to load resource: the server responded with a status of 404 (Not Found)', timestamp: 1524122678393, type: '' }) to equal undefined.
[1]     Expected $[1] = Entry({ level: SEVERE, message: 'http://localhost:8080/bundle.js - Failed to load resource: the server responded with a status of 404 (Not Found)', timestamp: 1524122678406, type: '' }) to equal undefined.
[1]     Expected $[2] = Entry({ level: SEVERE, message: 'http://localhost:8080/ - Refusedto execute script from 'http://localhost:8080/bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.', timestamp: 1524122678406, type: '' }) to equal undefined.
[1]   Stack:
[1]     Error: Failed expectation
[1]         at /Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/e2e/app.e2e-spec.ts:9:26
[1]         at ManagedPromise.invokeCallback_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:1366:14)
[1]         at TaskQueue.execute_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2970:14)
[1]         at TaskQueue.executeNext_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2953:27)
[1]         at asyncRun (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2813:27)
[1]         at /Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:676:7
[1]         at <anonymous>
[1]         at process._tickCallback (internal/process/next_tick.js:188:7)
[1]
[1] 2) QuickStart Lib E2E Tests should display meaning
[1]   Message:
[1]     Failed: Angular could not be found on the page http://localhost:8080/.If this is not an Angular application, you may need to turn off waiting for Angular.
[1]                               Please see
[1]                               https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
[1]   Stack:
[1]     Error: Angular could not be found on the page http://localhost:8080/.If this is not an Angular application, you may need to turn off waiting for Angular.
[1]                               Please see
[1]                               https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
[1]         at executeAsyncScript_.then (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/protractor/lib/browser.ts:936:29)
[1]         at ManagedPromise.invokeCallback_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:1366:14)
[1]         at TaskQueue.execute_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2970:14)
[1]         at TaskQueue.executeNext_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2953:27)
[1]         at asyncRun (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2813:27)
[1]         at /Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:676:7
[1]         at <anonymous>
[1]         at process._tickCallback (internal/process/next_tick.js:188:7)
[1]     From: Task: Run beforeEach in control flow
[1]         at UserContext.<anonymous> (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/jasminewd2/index.js:94:19)
[1]     From asynchronous test:
[1]     Error
[1]         at Suite.<anonymous> (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/e2e/app.e2e-spec.ts:5:3)
[1]         at Object.<anonymous> (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/e2e/app.e2e-spec.ts:3:1)
[1]         at Module._compile (module.js:652:30)
[1]         at Object.Module._extensions..js (module.js:663:10)
[1]         at Module.load (module.js:565:32)
[1]         at tryModuleLoad (module.js:505:12)
[1]   Message:
[1]     Failed: Error while waiting for Protractor to sync with the page: "window.angularis undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
[1]   Stack:
[1]     Error: Error while waiting for Protractor to sync with the page: "window.angular is undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
[1]         at runWaitForAngularScript.then (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/protractor/lib/browser.ts:653:19)
[1]         at ManagedPromise.invokeCallback_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:1366:14)
[1]         at TaskQueue.execute_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2970:14)
[1]         at TaskQueue.executeNext_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2953:27)
[1]         at asyncRun (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2813:27)
[1]         at /Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:676:7
[1]         at <anonymous>
[1]         at process._tickCallback (internal/process/next_tick.js:188:7)Error
[1]         at ElementArrayFinder.applyAction_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/protractor/lib/element.ts:482:23)
[1]         at ElementArrayFinder.(anonymous function).args [as getText] (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/protractor/lib/element.ts:96:21)
[1]         at ElementFinder.(anonymous function).args [as getText] (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/protractor/lib/element.ts:873:14)
[1]         at UserContext.<anonymous> (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/e2e/app.e2e-spec.ts:18:34)
[1]         at /Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/jasminewd2/index.js:112:25
[1]         at new ManagedPromise (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:1067:7)
[1]         at ControlFlow.promise (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2396:12)
[1]         at schedulerExecute (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/jasminewd2/index.js:95:18)
[1]         at TaskQueue.execute_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2970:14)
[1]         at TaskQueue.executeNext_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2953:27)
[1]     From: Task: Run it("should display meaning") in control flow
[1]         at UserContext.<anonymous> (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/jasminewd2/index.js:94:19)
[1]         at /Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/jasminewd2/index.js:64:48
[1]         at ControlFlow.emit (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/events.js:62:21)
[1]         at ControlFlow.shutdown_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2565:10)
[1]     From asynchronous test:
[1]     Error
[1]         at Suite.<anonymous> (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/e2e/app.e2e-spec.ts:17:3)
[1]         at Object.<anonymous> (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/e2e/app.e2e-spec.ts:3:1)
[1]         at Module._compile (module.js:652:30)
[1]         at Object.Module._extensions..js (module.js:663:10)
[1]         at Module.load (module.js:565:32)
[1]         at tryModuleLoad (module.js:505:12)
[1]   Message:
[1]     Expected $.length = 2 to equal 0.
[1]     Expected $[0] = Entry({ level: SEVERE, message: 'http://localhost:8080/bundle.js - Failed to load resource: the server responded with a status of 404 (Not Found)', timestamp: 1524122688669, type: '' }) to equal undefined.
    Expected $[1] = Entry({ level: SEVERE, message: 'http://localhost:8080/ - Refused to execute script from 'http://localhost:8080/bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.', timestamp: 1524122688669, type: '' }) to equal undefined.
[1]   Stack:
[1]     Error: Failed expectation
[1]         at /Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/e2e/app.e2e-spec.ts:9:26
[1]         at ManagedPromise.invokeCallback_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:1366:14)
[1]         at TaskQueue.execute_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2970:14)
[1]         at TaskQueue.executeNext_ (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2953:27)
[1]         at asyncRun (/Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:2813:27)
[1]         at /Users/muthaiahthiagarajan/Downloads/angular-quickstart-lib-master/integration/node_modules/selenium-webdriver/lib/promise.js:676:7
[1]         at <anonymous>
[1]         at process._tickCallback (internal/process/next_tick.js:188:7)
[1]
[1] 2 specs, 2 failures
[1] Finished in 20.523 seconds
[1]
[1] [12:54:58] I/launcher - 0 instance(s) of WebDriver still running
[1] [12:54:58] I/launcher - chrome #01 failed 2 test(s)
[1] [12:54:58] I/launcher - overall: 2 failed spec(s)
[1] [12:54:58] E/launcher - Process exited with error code 1
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! integration-test@1.0.0 protractor: `protractor protractor.config.js`
[1] npm ERR! Exit status 1
[1] npm ERR!
npm ERR! Failed at the integration-test@1.0.0 protractor script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /Users/muthaiahthiagarajan/.npm/_logs/2018-04-19T07_24_58_904Z-debug.log
[1] npm run protractor exited with code 1
--> Sending SIGTERM to other processes..
[0] npm run serve:e2e-aot exited with code null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integration-test@1.0.0 e2e:aot: `concurrently "npm run serve:e2e-aot" "npm run protractor" --kill-others --success first`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integration-test@1.0.0 e2e:aot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/muthaiahthiagarajan/.npm/_logs/2018-04-19T07_24_58_981Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! quickstart-lib@1.0.0 integration:aot: `cd integration && npm run e2e:aot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the quickstart-lib@1.0.0 integration:aot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/muthaiahthiagarajan/.npm/_logs/2018-04-19T07_24_58_996Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! quickstart-lib@1.0.0 integration: `npm run integration:aot && npm run integration:jit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the quickstart-lib@1.0.0 integration script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/muthaiahthiagarajan/.npm/_logs/2018-04-19T07_24_59_012Z-debug.log

**Comment by onadikuda** [comment]
I'm facing the same above issue and unable to find a fix. Can anyone help us in finding the solution?

**Comment by muhammedgaygisiz** [comment]
Same here :/

**Comment by muhammedgaygisiz** [comment]
I guess this is a duplicate of #41
